### PR TITLE
Process unsupported EXIF rotation tag files

### PR DESCRIPTION
**Pull request by fasih**

### CODE REVIEW

**Comment by josch** [comment]
I don't understand. This is hiding a problem with the input. Instead of throwing an error this change allows processing potentially corrupt files.

Also, the upstream git repo is at https://gitlab.mister-muffin.de/josch/img2pdf/

**Comment by AIT-AT** [comment]
I have the same problem as fasih. I get some images with "Orientation == 0". And this is not covered by your code. So this change does not hide a problem, but makes the programming more tolerant to errors.

**Comment by josch** [comment]
@AIT-AT how does running img2pdf with `--rotation=ifvalid` not solve the problem for you?

**Comment by AIT-AT** [comment]
I run the code in a python script. And for example HUAWAI sets the image rotation orientation==0
```
with open(pdf,"wb") as f:
        f.write(img2pdf.convert(str(image)))
```

**Comment by josch** [comment]
@AIT-AT try this:

```python
with open(pdf,"wb") as f:
        f.write(img2pdf.convert(str(image), rotation=img2pdf.Rotation.ifvalid))
```

**Comment by mara004** [comment]
Maybe it would make sense to have `ifvalid` as default? I think this is the behaviour most users would want/expect.

**Comment by AIT-AT** [comment]
@josch this works. However, you can then ignore all orientations except 1, 6, 3 and 8.

**Comment by josch** [comment]
@AIT-AT Yes, ifvalid ignores all rotations other than the valid ones. That's specifically what the option value was introduced for. Do you need something else? What is your use-case? If img2pdf cannot do something that you want it to do, can you open a new issue specifically about that?

@mara004 `ifvalid` could be made the default but I don't really like the idea. Think about the alternative: if img2pdf would ignore rotation values that are not meaningful by default then people would never notice that there is something wrong with their input. By having to manually state "please ignore invalid rotation values" the user gives explicit consent that they want this behavior and thus won't caught by surprise later on. Software that produces invalid rotation values will never get fixed if software consuming images doesn't show that there is a problem. If img2pdf would also silently ignore faulty rotation values, then img2pdf would be part of the problem and perpetuate bad software producing these images. I don't want img2pdf to be part of the problem. Thus I think that if a user of img2pdf really wants to ignore the problem, then they should explicitly have to state so. I definitely want to improve the documentation of the `ifvalid` value so that users of img2pdf will have an easier time finding out what to do if they want to ignore bad rotation values. I'm also considering adding a configuration file to img2pdf. That way, users could globally state that they want to ignore bad rotation values instead of always having to pass `--rotation=ifvalid` to their img2pdf calls.

**Comment by josch** [comment]
@mara004 I just made it more obvious what to do when running into invalid rotation values in 3da370d3bd4a04822bf0a7611a55ab7eb0beff48

**Comment by mara004** [comment]
> Think about the alternative: if img2pdf would ignore rotation values that are not meaningful by default then people would never notice that there is something wrong with their input.

Why isn't a warning sufficient to inform users about invalid or unsupported rotation?

**Comment by mara004** [comment]
> Think about the alternative: if img2pdf would ignore rotation values that are not meaningful by default then people would never notice that there is something wrong with their input.

Why isn't a warning sufficient to inform users about invalid or unsupported rotation?
In general, I support the paradigm that libraries should strictly adhere to specifications when writing, but that they should be as tolerant as possible when reading.

Another issue to consider is that img2pdf is quite bloated already, and adding options or configuration files to work around questionable defaults would make that situation worse.

**Comment by josch** [comment]
> Why isn't a warning sufficient to inform users about invalid or unsupported rotation? In general, I support the paradigm that libraries should strictly adhere to specifications when writing, but that they should be as tolerant as possible when reading.

Because img2pdf is used in situation were such a warning would never be seen.

> Another issue to consider is that img2pdf is quite bloated already, and adding options or configuration files to work around questionable defaults would make that situation worse.

The complexity would not go away by choosing a different default because you'd still need that complexity to choose the setting that is not the default.

**Comment by mara004** [comment]
> The complexity would not go away by choosing a different default because you'd still need that complexity to choose the setting that is not the default.

Well, depends on whether the option is necessary at all. Provided that `ifvalid` were be the default, I'd consider the `Rotation` option bloat. Of course configurability is a thing, but in this case it doesn't offer a benefit for users while only increasing complexity.

> Because img2pdf is used in situation were such a warning would never be seen.

In such a situation, users most probably wouldn't see the exception, either, and never see the reason why processing their image failed. I'd say it is up to embedders to implement a meaningful log panel where such warnings would be shown.

**Pull request closed without merging**
