### PR TITLE
adjust page orientations when multiple files are processed

### PR DESCRIPTION
**Pull request by xiota**
When multiple images are processed and --pagesize is specified, adjust the orientation of each page to match the input image.  Adjustments are based on the orientation of the first page in case the user actually intends to stretch the images.

For example, in a directory with images: 1-portrait.png and 2-landscape.png, img2pdf -s 612x -o output.pdf *.png will result in a pdf where the first page 8.5in x11in and the second page 11in x 8.5in.  Previously, the second page would have been 8.5in x6.568in.

### CODE REVIEW

**Comment by josch** [comment]
Isn't this specifically the amount of feature creep you wanted to avoid in issue 28? ;)

I'd say, if the user wants a page size of XxY units then all pages should have that size and not produce some pages with a size of YxX instead.

If you want that, then just run img2pdf for each image separately and give the --pagesize option for each input image as you desire and concatenate the output with pdftk.

**Comment by xiota** [comment]
I wouldn't consider this feature creep, but rather a correcting behavior that is probably unwanted in the first place.  Suppose you have a hundred images in a directory with various orientations.

* If we call img2pdf -s 612x792 -o output.pdf *.jpg, the portrait pages will be oriented correctly, but the landscape pages will be distorted to fit the portrait orientation.

* If we use 792x612, the portrait pages will be distorted and the landscape pages will be correct.

* If we use 612x, the landscape pages will not be the correct size (too small).

* If we use x792, the portrait pages will be the wrong size (too big).

Are any of the above ever actually the desired result?

To run img2pdf with different options for each image would require examining each image separately.  This could be done with the file command, parsing out the dimensions, making appropriate calculations, etc.  Which will slow down the process (since each file will now have to be read and processed twice).

On the other hand, since the orientation correction is based on the first image of the series, if the above distortions are desired, img2pdf can be run separately on each image without having to process each file to figure out its orientation:

for i in *.jpg ; do
 img2pdf -s 612x792 -o "tmp_$i.pdf" "$i"
done

**Comment by josch** [comment]
Okay, I see your point. Thanks for clarifying it.

I'd still argue that somebody who says -s 612x792 will *really* want exactly that dimension for all their input images and that somebody who says -s 612x will *really* want all their output pages to be 612 units in width.

But I see how the alternative to loop through all images outside and decide in a case-by-case basis would be quite the hassle and how this scenario can actually be quite common.

I see two solutions which could make us both happy.

1. add a --auto-orientation option or a --no-auto-orientation option which either auto-orients (as in your pull request) or doesn't do it depending on which version is picked to be the default
2. make the --pagesize parameter understand something like imagemagick's geometry syntax http://www.imagemagick.org/script/command-line-processing.php#geometry That way, your problem would be solved by giving --pagesize 792x792^ which would fit the image into this square independent of its orientation

I like the second solution more. What do you think?

**Comment by xiota** [comment]
For the first solution, would auto orient also adjust the orientation of the first page?

I also like the second solution, but what if someone actually wants the distorted output without keeping the aspect ratio?

**Comment by xiota** [comment]
Haha.  I just noticed the "^" symbol...

**Comment by josch** [comment]
Ah yes, sorry I was pondering whether I should point out the "^" or not because it can easily be overlooked :)

As I said, I like the second option more because it potentially requires less learning (imagemagick users will feel at home) instead of inventing something new (like yet another commandline option).

Would you feel that this solution fixes your problem? In that case you can close this pull request.

You can then either wait until I implemented that feature (please open a bug about it) or open a new pull request implementing it :)

**Pull request closed without merging**
