### PR TITLE
Update

### PR DESCRIPTION
**Pull request by lukahn**
Updated img2pdf to allow custom x and y resolutions.
Updated README to reflect use as a library.

### CODE REVIEW

**Comment by lukahn** [comment]
Heya. Thanks for the speedy reply. I'll make the necessary changes when I'm back on Monday.

**Comment by lukahn** [comment]
Heya. I've made the necessary changes, so just let me know if it looks all right to you.

**Comment by josch** [comment]
What I meant was, that you split the original commit into two, not that you make a commit reverting the original commit and then add two which are like the first but split.

**Comment by lukahn** [comment]
What would you like me to do exactly? If you like then I can cancel this pull request, create a new fork, and then add the two commits individually as I've done above (omitting the revert stage).

**Comment by josch** [comment]
Git allows you to rewrite the history (using git rebase) but in your case, since this is the last commit you'd just `git reset HEAD^` to go back to HEAD's parent and then individually commit your changes using `git add` (with -p as needed). Then you'd push your new history with `git push -f` to overwrite the old history.

If you are unfamiliar with git, then I can do this myself, too.

**Comment by lukahn** [comment]
Heya. Thanks for your help in guiding me through the process. I've made the changes to reflect two commits since the master. Let me know if this looks okay.

**Comment by josch** [comment]
It does. Thanks for reworking these commits and welcome to git :)

**Pull request merged**
